FROM node:16-alpine

WORKDIR '/app'


#COPY package.json .
COPY --chown=node:node package.json .

RUN npm install

RUN mkdir 'node_modules/.cache'
RUN chown -R node:node node_modules

#COPY . .
COPY --chown=node:node . .

RUN npm install -g npm@8.3.0

USER node

CMD ["npm", "run", "start"]
